import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/src/app/globals.css";
import { QueryProvider } from "@/src/providers/tanstack-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Header from "@/src/components/header/Header";
import Footer from "@/src/components/footer/Footer";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <NuqsAdapter>
            <Header />
            {children}
            <Footer />
            <Toaster position="top-center" richColors duration={2500} />
          </NuqsAdapter>
        </QueryProvider>
      </body>
    </html>
  );
}
